export const RESET_DECIMAL = 'RESET_DECIMAL'
export const CONVERT_DECIMAL_REQUEST = 'CONVERT_DECIMAL_REQUEST'
export const CONVERT_DECIMAL_SUCCESS = 'CONVERT_DECIMAL_SUCCESS'
export const CONVERT_DECIMAL_FAILURE = 'CONVERT_DECIMAL_FAILURE'
